sensor:
  - platform: synologydsm
    host: 192.168.1.14
    username: !secret synology_username
    password: !secret synology_password
    volumes:
      - volume_1
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
