title: Home
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/car.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/master_bedroom.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/cameras.yaml